version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
##      - MYSQL_DATABASE: $MYSQLDB_DATABASE
##      - MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: Rf412..Ellsdc.5896safkk

    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

    volumes:
      - db:/var/lib/mysql
    networks:
      - cocoon-network
  accounting:
    depends_on:
      - db
    build: .
    image: bahadockerhub/cocoonapp:01
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    #      - 9095:9095
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://n1nlmysql55plsk.secureserver.net:3306/cacoon_accounting?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - cocoon-network

volumes:
  db:

networks:
  cocoon-network: